# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux Kernel SOC specific device drivers.
#
#ifdef ODM_WT_EDIT
#Bin.Su@ODM_WT.BSP.Boardid,2019/05/07,Add device info for RM begain
obj-$(CONFIG_ODM_RM_DEVICEINFO)		+= oppo_devinfo/device_info.o
obj-$(CONFIG_ODM_RM_DEVICEINFO)		+= oppoversion/oppoversion.o
#Bin.Su@ODM_WT.BSP.Boardid,2019/05/07,Add device info for RM end
#endif
