#/*************************************************************************
# * ** Copyright (C), 2008-2016, OPPO Mobile Comm Corp., Ltd.
# * ** ODM_WT_EDIT
# * ** File: - Makefile
# * ** Description: Add for bootloader log
# * ** Version: 1.0
# * ** Date : 2019/04/20
# * ** Author: Hui.Wang@ODM_WT.BSP.Kernel.Stability
# * **
# * ** ------------------- Revision History: -------------------------------
# * **    <author>       <data>         <version >      <desc>
# * **    Hui.Wang       2019/04/20     1.0             build this module
# * **********************************************************************/

obj-$(CONFIG_WT_SYSTEM)		+= wt_system_main.o
obj-$(CONFIG_WT_BOOTLOADER_LOG)	+= wt_bootloader_log/wt_bootloader_log_save.o
obj-$(CONFIG_WT_BOOT_REASON)	+= wt_boot_reason/wt_boot_reason.o
