# Version: 1.0
# Date : 2018/5/14
# Author: Zhonghua.Hu@ODM_WT.BSP.TP-FP.TP
#
# -------------------------Revision History:----------------------------------
#  <author>	 <data> 	<version >			<desc>
#
#
#*****************************************************************************/
obj-$(CONFIG_TOUCHSCREEN_ILI9881H) += ilitek_main.o \
                                      ilitek_spi.o \
									  ilitek_plat_qcom.o \
									  ilitek_ic.o \
									  ilitek_touch.o \
									  ilitek_mp.o \
									  ilitek_fw.o \
									  ilitek_node.o	\
									  oppo_node.o